package todr.mybatis.model;

public class Producer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCER.ID
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCER.NAME
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCER.ID
     *
     * @return the value of PUBLIC.PRODUCER.ID
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCER.ID
     *
     * @param id the value for PUBLIC.PRODUCER.ID
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCER.NAME
     *
     * @return the value of PUBLIC.PRODUCER.NAME
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCER.NAME
     *
     * @param name the value for PUBLIC.PRODUCER.NAME
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}