package todr.mybatis.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.PRODUCER_ID
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    private Integer producerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.OPT_LOCK_VERSION
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    private Integer optLockVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.ID
     *
     * @return the value of PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.ID
     *
     * @param id the value for PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.NAME
     *
     * @return the value of PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.NAME
     *
     * @param name the value for PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.PRICE
     *
     * @return the value of PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.PRICE
     *
     * @param price the value for PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.PRODUCER_ID
     *
     * @return the value of PUBLIC.PRODUCT.PRODUCER_ID
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public Integer getProducerId() {
        return producerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.PRODUCER_ID
     *
     * @param producerId the value for PUBLIC.PRODUCT.PRODUCER_ID
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public void setProducerId(Integer producerId) {
        this.producerId = producerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.OPT_LOCK_VERSION
     *
     * @return the value of PUBLIC.PRODUCT.OPT_LOCK_VERSION
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public Integer getOptLockVersion() {
        return optLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.OPT_LOCK_VERSION
     *
     * @param optLockVersion the value for PUBLIC.PRODUCT.OPT_LOCK_VERSION
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    public void setOptLockVersion(Integer optLockVersion) {
        this.optLockVersion = optLockVersion;
    }
}