package todr.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import todr.mybatis.model.Producer;

@Mapper
public interface ProducerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    int insert(Producer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    Producer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    List<Producer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    int updateByPrimaryKey(Producer record);
}