package todr.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import todr.mybatis.model.Receiver;

@Mapper
public interface ReceiverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECEIVER
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECEIVER
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    int insert(Receiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECEIVER
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    Receiver selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECEIVER
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    List<Receiver> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECEIVER
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    int updateByPrimaryKey(Receiver record);
}