package todr.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import todr.mybatis.model.ReceiverProduct;

@Mapper
public interface ReceiverProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECEIVER_PRODUCT
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    int insert(ReceiverProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECEIVER_PRODUCT
     *
     * @mbg.generated Thu Mar 26 18:25:57 EET 2020
     */
    List<ReceiverProduct> selectAll();
}